services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - tech-challenge-fiap
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tech-challenge-db'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - 5432
    networks:
        - tech-challenge-fiap
  backend:
    image: brunoalbubrito/tech-challenge-pagamento
    environment:
      - 'DB_HOST=db'
      - 'DB_NAME=tech-challenge-db'
      - 'DB_USERNAME=myuser'
      - 'DB_PASSWORD=secret'
    ports:
      - 8084:8080
    networks:
        - tech-challenge-fiap
    depends_on:
      - db
      - rabbitmq

  pedido-service:
    image: edsjunior7/tech-challenge-pedido
    ports:
      - 8085:80
    environment:
      - 'DB_HOST=db'
      - 'DB_NAME=tech-challenge-db'
      - 'DB_USERNAME=myuser'
      - 'DB_PASSWORD=secret'
      - 'RABBITMQ_HOST=rabbitmq'
      - 'RABBITMQ_USER=user'
      - 'RABBITMQ_PASS=password'
    networks:
      - tech-challenge-fiap
    depends_on:
      - db
      - rabbitmq
networks:
  tech-challenge-fiap:
    driver: bridge